### ISSUE TITLE
如何持久化

### ISSUE THREAD

**Issue by shellus** [SuLingGG/OpenWrt-Rpi-Docker#52]
搜索了一下，两个相关的issue并没有解决这个问题
尝试对比安装插件前和安装插件后，得到产生变化的目录
/bin
/lib
/etc
/usr/bin
/usr/lib
/usr/share
/usr/libexec
/usr/sbin

如果从容器拷贝文件出来并影射了这些目录，再次启动会有一堆报错，估计是软链接或者特殊文件产生的问题

所以，到底应该怎么实现持久化呢？

这是我的docker-compose文件

```
version: "2"
services:
  lede:
    image: suling/openwrt-mini:x86_64
    privileged: true
    volumes:
      - ./data/bin:/bin
      - ./data/lib:/lib
      - ./data/etc:/etc
      - ./data/usr/bin:/usr/bin
      - ./data/usr/lib:/usr/lib
      - ./data/usr/share:/usr/share
      - ./data/usr/libexec:/usr/libexec
      - ./data/usr/sbin:/usr/sbin
    privileged: true
    networks:
      - macvlan
    restart: unless-stopped

networks:
  macvlan:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: '192.168.1.0/24'
          gateway: '192.168.1.1'
```
